Repository woowacourse-teams/2020-songpa-people, pull requests merged in 2020-09, with the labels that each got.

#233 [FEAT] 블루그린 무중단 배포 적용
  build.gradle
  hashtagmap-web/build.gradle
  hashtagmap-web/src/main/java/com/songpapeople/hashtagmap/controller/WebRestController.java
  hashtagmap-web/src/main/resources/application.yml
  hashtagmap-web/src/main/resources/logback-spring.xml
  hashtagmap-web/src/test/java/com/songpapeople/hashtagmap/controller/WebRestControllerTest.java
  script/deploy.sh
  script/nonstop-deploy.sh
  script/nonstopweb/publish-over-ssh.sh
  script/nonstopweb/web-bind.sh
Labels: ⚙️ Infra

#234 [REFACTOR] Event Producer/Consumer 구조로 카카오 스케쥴링 개선하기
  hashtagmap-admin/front/src/components/blacklist/UpdateInstagramAfterAddBlackListForm.vue
  hashtagmap-admin/front/src/request/api/blackList.js
  hashtagmap-admin/src/test/java/com/songpapeople/hashtagmap/kakao/api/KakaoSchedulerApiControllerExceptionTest.java
  hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/event/model/EventHistory.java
  hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/event/model/EventStatus.java
  hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/event/model/KakaoEventHistory.java
  hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/event/repository/EventHistoryRepository.java
  hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/event/repository/KakaoEventHistoryRepository.java
  hashtagmap-core/src/test/java/com/songpapeople/hashtagmap/event/model/KakaoEventHistoryTest.java
  hashtagmap-event/build.gradle
  hashtagmap-event/src/main/java/com/songpapeople/hashtagmap/event/config/EventConfiguration.java
  hashtagmap-event/src/main/java/com/songpapeople/hashtagmap/event/message/Event.java
  hashtagmap-event/src/main/java/com/songpapeople/hashtagmap/event/message/KakaoEvent.java
  hashtagmap-event/src/main/java/com/songpapeople/hashtagmap/event/process/EventBroker.java
  hashtagmap-event/src/main/java/com/songpapeople/hashtagmap/event/process/EventBrokerGroup.java
  hashtagmap-event/src/main/java/com/songpapeople/hashtagmap/event/process/EventConsumer.java
  hashtagmap-event/src/main/java/com/songpapeople/hashtagmap/event/process/EventThreadPoolExecutor.java
  hashtagmap-event/src/main/java/com/songpapeople/hashtagmap/event/process/EventType.java
  hashtagmap-event/src/main/java/com/songpapeople/hashtagmap/event/service/EventService.java
  hashtagmap-event/src/test/java/com/songpapeople/hashtagmap/HashtagmapEventTestApplication.java
  hashtagmap-event/src/test/java/com/songpapeople/hashtagmap/event/process/EventConsumerTest.java
  hashtagmap-event/src/test/java/com/songpapeople/hashtagmap/event/process/EventTypeTest.java
  hashtagmap-instagram-crawler/src/test/resources/crawling-mock-data.txt
  hashtagmap-kakao-scheduler/build.gradle
  hashtagmap-kakao-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/config/KakaoSchedulerConfig.java
  hashtagmap-kakao-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/domain/KakaoSchedulerTask.java
  hashtagmap-kakao-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/domain/event/service/KakaoEventService.java
  hashtagmap-kakao-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/exception/KakaoSchedulerException.java
  hashtagmap-kakao-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/domain/KakaoSchedulerTaskMockTest.java
  hashtagmap-kakao-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/domain/KakaoSchedulerTaskTest.java
  hashtagmap-kakao-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/domain/KakaoSchedulerTest.java
  hashtagmap-kakao-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/domain/event/service/KakaoEventServiceTest.java
  hashtagmap-kakao-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/domain/factory/RectFactoryTest.java
  hashtagmap-web/front/src/components/TextBalloon.vue
  settings.gradle
Labels: 👷‍♂️ Admin, 💡 Feature, 🔍 Review Needed, 🛠 Refactoring

#238 [FEAT] 정적 리소스 캐싱
  hashtagmap-web/src/main/java/com/songpapeople/hashtagmap/config/StaticResourcePath.java
  hashtagmap-web/src/main/java/com/songpapeople/hashtagmap/config/WebMvcConfiguration.java
  hashtagmap-web/src/main/resources/application.yml
  hashtagmap-web/src/test/java/com/songpapeople/hashtagmap/web/StaticResourceTest.java
Labels: 🔍 Review Needed

#242 [FEAT] SonarQube 설치
  build.gradle
  hashtagmap-admin/build.gradle
  hashtagmap-batch/build.gradle
  hashtagmap-core/build.gradle
  hashtagmap-event/build.gradle
  hashtagmap-instagram-crawler/build.gradle
  hashtagmap-instagram-scheduler/build.gradle
  hashtagmap-kakao-api/build.gradle
  hashtagmap-kakao-scheduler/build.gradle
  hashtagmap-web/build.gradle
Labels: ⚙️ Infra, 💡 Feature

#249 [REFACTOR] 누락 테스트 작성 core 모듈
  .github/PULL_REQUEST_TEMPLATE.md
  hashtagmap-batch/build.gradle
  hashtagmap-core/build.gradle
  hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/blacklist/domain/model/BlackList.java
  hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/exception/CoreException.java
  hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/kakao/schedule/model/Schedule.java
  hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/member/model/AdminMember.java
  hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/place/domain/model/Place.java
  hashtagmap-core/src/test/java/com/songpapeople/hashtagmap/blacklist/domain/model/BlackListTest.java
  hashtagmap-core/src/test/java/com/songpapeople/hashtagmap/instagram/domain/model/InstagramTest.java
  hashtagmap-core/src/test/java/com/songpapeople/hashtagmap/instagram/domain/repository/InstagramRepositoryCustomImplTest.java
  hashtagmap-core/src/test/java/com/songpapeople/hashtagmap/kakao/schedule/model/PeriodHistoryTest.java
  hashtagmap-core/src/test/java/com/songpapeople/hashtagmap/kakao/schedule/model/ScheduleTest.java
  hashtagmap-core/src/test/java/com/songpapeople/hashtagmap/member/model/AdminMemberTest.java
  hashtagmap-core/src/test/java/com/songpapeople/hashtagmap/place/domain/model/CategoryTest.java
  hashtagmap-core/src/test/java/com/songpapeople/hashtagmap/place/domain/model/DistrictTest.java
  hashtagmap-core/src/test/java/com/songpapeople/hashtagmap/place/domain/model/ZoneTest.java
  hashtagmap-core/src/test/java/com/songpapeople/hashtagmap/taglevel/model/TagLevelsTest.java
  hashtagmap-web/src/main/java/com/songpapeople/hashtagmap/config/WebMvcConfiguration.java
Labels: 🔍 Review Needed, 🛠 Refactoring

#251 [REFACTOR] 애플 제품에서 모달 디자인 수정
  hashtagmap-web/front/src/components/detail-modal/DetailModal.vue
Labels: 🏞 View, 🔍 Review Needed, 🛠 Refactoring

#253 [REFACTOR] kakao api 모듈 테스트 커버리지 90%이상 되도록
  hashtagmap-kakao-api/build.gradle
  hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/domain/rect/Rect.java
  hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/exception/KakaoApiException.java
  hashtagmap-kakao-api/src/main/java/com/songpapeople/hashtagmap/kakaoapi/service/KakaoApiService.java
  hashtagmap-kakao-api/src/test/java/com/songpapeople/hashtagmap/kakaoapi/domain/KakaoPlaceDtoFixture.java
  hashtagmap-kakao-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/domain/event/service/KakaoEventService.java
Labels: 🔍 Review Needed, 🛠 Refactoring

#252 [REFACTOR] 누락 테스트 작성 event, insta-crawler
  hashtagmap-event/build.gradle
  hashtagmap-event/src/main/java/com/songpapeople/hashtagmap/event/message/Event.java
  hashtagmap-event/src/main/java/com/songpapeople/hashtagmap/event/message/KakaoEvent.java
  hashtagmap-event/src/main/java/com/songpapeople/hashtagmap/event/process/EventConsumer.java
  hashtagmap-event/src/main/java/com/songpapeople/hashtagmap/event/process/EventThreadPoolExecutor.java
  hashtagmap-event/src/main/java/com/songpapeople/hashtagmap/event/service/EventService.java
  hashtagmap-event/src/test/java/com/songpapeople/hashtagmap/event/message/KakaoEventTest.java
  hashtagmap-event/src/test/java/com/songpapeople/hashtagmap/event/process/EventConsumerTest.java
  hashtagmap-instagram-crawler/build.gradle
  hashtagmap-instagram-crawler/src/main/java/com/songpapeople/hashtagmap/crawler/InstaCrawlingResult.java
  hashtagmap-instagram-crawler/src/main/java/com/songpapeople/hashtagmap/crawler/JsonExplorer.java
  hashtagmap-instagram-crawler/src/main/java/com/songpapeople/hashtagmap/crawler/RegexPattern.java
  hashtagmap-instagram-crawler/src/main/java/com/songpapeople/hashtagmap/proxy/ProxiesFactory.java
  hashtagmap-instagram-crawler/src/main/java/com/songpapeople/hashtagmap/util/PlaceNameParser.java
  hashtagmap-instagram-crawler/src/test/java/com/songpapeople/hashtagmap/MockDataFactory.java
  hashtagmap-instagram-crawler/src/test/java/com/songpapeople/hashtagmap/MockDataFactoryTest.java
  hashtagmap-instagram-crawler/src/test/java/com/songpapeople/hashtagmap/crawler/InstaCrawlingResultTest.java
  hashtagmap-instagram-crawler/src/test/java/com/songpapeople/hashtagmap/crawler/InstagramCrawlerTest.java
  hashtagmap-instagram-crawler/src/test/java/com/songpapeople/hashtagmap/crawler/JsonExplorerTest.java
  hashtagmap-instagram-crawler/src/test/java/com/songpapeople/hashtagmap/proxy/ProxiesFactoryTest.java
  hashtagmap-instagram-crawler/src/test/java/com/songpapeople/hashtagmap/util/PlaceNameParserTest.java
  hashtagmap-kakao-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/domain/KakaoSchedulerTask.java
  hashtagmap-kakao-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/domain/event/service/KakaoEventService.java
  hashtagmap-kakao-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/domain/KakaoSchedulerTaskMockTest.java
  hashtagmap-kakao-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/domain/event/service/KakaoEventServiceTest.java
Labels: 🔍 Review Needed, 🛠 Refactoring

#259 [REFACTOR] 인스타그램 스케줄러 테스트 추가
  hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/blacklist/domain/model/BlackList.java
  hashtagmap-instagram-scheduler/build.gradle
  hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/exception/InstagramSchedulerExceptionStatus.java
  hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/CrawlerWithProxy.java
  hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/InstagramScheduleService.java
  hashtagmap-instagram-scheduler/src/main/java/com/songpapeople/hashtagmap/scheduler/SingleCrawlResult.java
  hashtagmap-instagram-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/CrawlerWithProxyTest.java
  hashtagmap-instagram-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/CrawlingResultTest.java
  hashtagmap-instagram-scheduler/src/test/java/com/songpapeople/hashtagmap/scheduler/InstagramScheduleServiceTest.java
Labels: 🔍 Review Needed, 🙋‍♂️ Answer Needed, 🛠 Refactoring

#262 [DOCS] hashtagmap-batch, hashtagmap-scheduler모듈의 README.md 작성
  build.gradle
  hashtagmap-batch/README.md
  hashtagmap-instagram-scheduler/README.md
Labels: 📚Docs, 🔍 Review Needed, 🙋‍♂️ Answer Needed

#255 [DOCS] hashtagmap-web, hashtagmap-instagram-crawler 모듈의 README.md 작성
  hashtagmap-instagram-crawler/README.md
  hashtagmap-web/README.md
Labels: 📚Docs, 🔍 Review Needed

#260 [DOCS] hashtagmap-common, hashtagmap-core 모듈 README.md 작성
  hashtagmap-common/README.md
  hashtagmap-core/README.md
Labels: 📚Docs, 🔍 Review Needed, 🙋‍♂️ Answer Needed

#264 [DOCS] kakao-api, kakao-scheduler README.md 작성
  hashtagmap-kakao-api/README.md
  hashtagmap-kakao-scheduler/README.md
Labels: 📚Docs, 🔍 Review Needed

#269 [REFACTOR] instagram-post image_url 데이터 포맷 변경
  hashtagmap-core/src/main/java/com/songpapeople/hashtagmap/instagram/domain/model/InstagramPost.java
Labels: ⚙️ Infra, 👷‍♂️ Admin, 🔍 Review Needed, 🛠 Refactoring

#272 [DOCS] 최상위 README.md 작성
  README.md
  hashtagmap-web/src/main/resources/application.yml
Labels: 📚Docs, 🔍 Review Needed

#276 [BUG] 소나큐브에서 검사한 버그 수정하기
  hashtagmap-admin/src/main/java/com/songpapeople/hashtagmap/member/api/MemberApiController.java
  hashtagmap-batch/src/main/java/com/songpapeople/hashtagmap/instagram/writer/InstagramBatchWriter.java
  hashtagmap-event/build.gradle
  hashtagmap-event/src/main/java/com/songpapeople/hashtagmap/event/process/EventThreadPoolExecutor.java
  hashtagmap-instagram-service/src/main/java/com/songpapeople/hashtagmap/service/InstagramService.java
Labels: 🧨 Bug

#279 [REFACTOR] 데모를 위한 버전 업
  hashtagmap-admin/build.gradle
  hashtagmap-web/build.gradle
Labels: 🛠 Refactoring
